#!/usr/bin/env bash
# Stable defaults for graph workloads. Set GRAPHATLAS_NUM_THREADS explicitly
# to use more CPU threads; inherited BLAS settings are intentionally replaced.
GRAPHATLAS_NUM_THREADS="${GRAPHATLAS_NUM_THREADS:-1}"
export OMP_NUM_THREADS="$GRAPHATLAS_NUM_THREADS"
export MKL_NUM_THREADS="$GRAPHATLAS_NUM_THREADS"
export OPENBLAS_NUM_THREADS="$GRAPHATLAS_NUM_THREADS"
export NUMEXPR_NUM_THREADS="$GRAPHATLAS_NUM_THREADS"
export VECLIB_MAXIMUM_THREADS="$GRAPHATLAS_NUM_THREADS"
export BLIS_NUM_THREADS="$GRAPHATLAS_NUM_THREADS"
export TOKENIZERS_PARALLELISM="false"
export PYTHONUTF8="${PYTHONUTF8:-1}"
export MPLBACKEND="${MPLBACKEND:-Agg}"
export MPLCONFIGDIR="${MPLCONFIGDIR:-$PWD/outputs/cache/matplotlib}"
export XDG_CACHE_HOME="${XDG_CACHE_HOME:-$PWD/outputs/cache/xdg}"
mkdir -p "$MPLCONFIGDIR" "$XDG_CACHE_HOME"
export PYTEST_DISABLE_PLUGIN_AUTOLOAD="${PYTEST_DISABLE_PLUGIN_AUTOLOAD:-1}"
export GRAPHATLAS_IN_PROCESS="${GRAPHATLAS_IN_PROCESS:-0}"
